language: python
python:
  - "2.7"
install:
  - pip install -r test_requirements.txt --use-mirror
  - pip install flake8 --use-mirrors
  - pip install -q . --use-mirrors
env:
  - PYFLAKES_BUILTINS="_"
before_script:
  - flake8 --show-source --ignore=E125 --statistics akanda test setup.py
script: nosetests -d